### ISSUE TITLE
PDBReader broken

### ISSUE THREAD

**Issue by daker** [Kitware/vtk-js#1842]
**Describe the bug**

The PDBReader example is broken, i am not sure if it's the example or reader itself.

Edit: This is caused by e32bcd8887734bdce8b4c177c58451a155c56e48

**To Reproduce**

1. Go to https://kitware.github.io/vtk-js/examples/PDBReader.html
2. See error

***Stack***

```js
Uncaught TypeError: TYPE_MAPPING[type] is not a function
    at Object.get (PDBReader.js:10803)
    at vtkPDBReader (PDBReader.js:10921)
    at extend (PDBReader.js:11077)
    at Object.constructor [as newInstance] (PDBReader.js:36174)
    at Module../IO/Misc/PDBReader/example/index.js (PDBReader.js:10849)
    at __webpack_require__ (PDBReader.js:43554)
    at PDBReader.js:43640
    at PDBReader.js:43642
```

***vtk.js version:***
v17.7.3

**Comment by daker** [comment]
All the classes using `DataAccessHelper` are broken

FYI @jourdain

**Comment by jourdain** [comment]
They just need an explicit import for the piece that we use. The idea was to allow tree shaking to occur and enable JSZip+Pako to be trimmed down if not needed.

Thanks for pointing it out.

**Comment by jourdain** [comment]
Fixed in 17.7.4
