### ISSUE TITLE
[Bug] KeyboardCameraManipulator: console errors

### ISSUE THREAD

**Issue by Jo-Byr** [Kitware/vtk-js#3660]
### Bug description

In KeyboardCameraManipulator example, 2 errors are thrown:

1) Uncaught (in promise) TypeError: publicAPI.startPointerLockInteraction is not a function

2) Uncaught TypeError: can't access property "cancelAnimation", model._interactor is undefined

### Steps to reproduce

npm run example KeyboardCameraManipulator

Click in the view to trigger the 1st error.

Press and release a key to trigger the 2nd.

### Detailed Behavior

The first error is due to the call to startPointerLockInteraction, introduced in e1fb07b and I don't think it referenced anything at the time either so I don't understand.

The second error is a typo, `model._interactor` should be `model.interactor`.

### Expected Behavior

To not have errors.

### Environment

- vtk.js version: 37.3.0
- Browsers: Firefox
- OS: Windows 11
